import type { Metadata } from "next";
import "./globals.css";
import "./styles/variables.css"

export const metadata: Metadata = {
  title: "최희연",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       
      >
        {children}
      </body>
    </html>
  );
}
